// Swiss Editorial & Minimalist Studio Pro Theme Styles

export const S: Record<string, any> = {
  // Official Document Sheet (Realistic A4 / US Letter)
  page: {
    backgroundColor: "#faf9f5",
    background: "#faf9f5",
    color: "#0f172a",
    colorScheme: "only light",
    forcedColorAdjust: "none",
    width: "100%",
    maxWidth: "760px",
    minHeight: "1020px",
    margin: "0 auto",
    padding: "48px 46px",
    position: "relative",
    fontFamily: "'Inter', -apple-system, sans-serif",
    fontSize: "12px",
    lineHeight: "1.55",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1), 0 20px 40px -10px rgba(0,0,0,0.5), 0 0 0 1px rgba(0,0,0,0.08)",
    borderRadius: "3px",
    border: "1px solid #e5e7eb",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  securityBorder: {
    position: "absolute",
    top: "14px",
    right: "14px",
    bottom: "14px",
    left: "14px",
    border: "1.5px double rgba(15, 23, 42, 0.15)",
    pointerEvents: "none",
    zIndex: 1,
  },
  microPrint: {
    position: "absolute",
    fontSize: "4px",
    color: "rgba(15, 23, 42, 0.2)",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    overflow: "hidden",
    fontFamily: "'JetBrains Mono', monospace",
  },
  header: {
    borderBottom: "2px solid #0f172a",
    paddingBottom: "18px",
    marginBottom: "22px",
    display: "flex",
    alignItems: "center",
    gap: "20px",
    position: "relative",
    zIndex: 2,
  },
  logoBox: {
    width: "74px",
    height: "74px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  instBlock: { flex: 1 },
  instName: {
    fontSize: "18px",
    fontWeight: "800",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "#0f172a",
    fontFamily: "'Cormorant Garamond', Georgia, serif",
    margin: 0,
    lineHeight: "1.2",
  },
  instSub: {
    fontSize: "11px",
    color: "#475569",
    margin: "3px 0 0",
    letterSpacing: "0.02em",
    fontFamily: "'Inter', sans-serif",
  },
  docTitle: {
    textAlign: "center",
    fontSize: "15px",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    margin: "18px 0",
    padding: "8px 0",
    borderTop: "1px solid #cbd5e1",
    borderBottom: "1px solid #cbd5e1",
    color: "#0f172a",
    fontFamily: "'Inter', sans-serif",
    position: "relative",
    zIndex: 2,
  },
  metaRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "11px",
    color: "#475569",
    marginBottom: "20px",
    fontFamily: "'JetBrains Mono', monospace",
    position: "relative",
    zIndex: 2,
  },
  section: { marginBottom: "18px", position: "relative", zIndex: 2 },
  sTitle: {
    fontSize: "11px",
    fontWeight: "700",
    color: "#0f172a",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "10px",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "4px",
    fontFamily: "'Inter', sans-serif",
  },
  fieldRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "4px 0",
    borderBottom: "1px dotted #e2e8f0",
  },
  fieldLabel: { color: "#64748b", fontWeight: "500", fontSize: "11px" },
  fieldVal: { fontWeight: "600", color: "#0f172a", fontSize: "11px" },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "10.5px",
    marginBottom: "16px",
    position: "relative",
    zIndex: 2,
  },
  th: {
    background: "#0f172a",
    color: "#ffffff",
    padding: "7px 10px",
    textAlign: "left",
    fontWeight: "700",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    fontSize: "9.5px",
    fontFamily: "'Inter', sans-serif",
  },
  td: {
    padding: "6px 10px",
    borderBottom: "1px solid #f1f5f9",
    color: "#1e293b",
  },
  tdAlt: {
    padding: "6px 10px",
    borderBottom: "1px solid #f1f5f9",
    color: "#1e293b",
    background: "rgba(241, 245, 249, 0.6)",
  },
  zebraEven: { background: "rgba(248, 250, 252, 0.6)" },
  zebraOdd: { background: "#ffffff" },
  totalRow: {
    background: "#f1f5f9",
    color: "#0f172a",
    fontWeight: "700",
    borderTop: "2px solid #0f172a",
  },
  infoBox: {
    background: "rgba(241, 245, 249, 0.7)",
    border: "1px solid #cbd5e1",
    borderLeft: "4px solid #0f172a",
    padding: "10px 14px",
    margin: "16px 0",
    fontSize: "11px",
    color: "#334155",
    borderRadius: "2px",
    position: "relative",
    zIndex: 2,
  },
  sigSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: "36px",
    paddingTop: "20px",
    position: "relative",
    zIndex: 2,
  },
  sigBlock: {
    width: "180px",
    textAlign: "center",
    position: "relative",
  },
  sigLine: {
    borderTop: "1px solid #0f172a",
    margin: "8px 0 6px 0",
  },
  sigLabel: {
    fontSize: "9.5px",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  // Authentic Registrar Stamp
  seal: {
    width: "104px",
    height: "104px",
    borderRadius: "50%",
    border: "2.5px solid #991b1b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#991b1b",
    transform: "rotate(-4deg)",
    mixBlendMode: "multiply",
    opacity: 0.88,
    boxShadow: "0 0 1px rgba(153, 27, 27, 0.5)",
  },
  watermark: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%,-50%) rotate(-32deg)",
    fontSize: "68px",
    fontWeight: "900",
    color: "rgba(15, 23, 42, 0.035)",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    pointerEvents: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
    zIndex: 0,
    fontFamily: "'Inter', sans-serif",
  },

  // ===== SWISS EDITORIAL STUDIO UI TOKENS =====
  ui: {
    fontFamily: "'Inter', -apple-system, sans-serif",
    bgStudio: "#080c14",
    panelBg: "#0d131f",
    panelBorder: "1px solid rgba(255, 255, 255, 0.08)",
    accentGold: "#d4af37",
    accentGoldLight: "#f3e5ab",
    accentEmerald: "#10b981",
    
    // Label & Input System
    label: {
      display: "block",
      fontSize: "10.5px",
      fontWeight: "700",
      color: "#94a3b8",
      marginBottom: "6px",
      textTransform: "uppercase",
      letterSpacing: "0.08em",
      fontFamily: "'JetBrains Mono', monospace",
    },
    input: {
      width: "100%",
      background: "#080c14",
      border: "1px solid #1e293b",
      borderRadius: "6px",
      padding: "10px 14px",
      color: "#f8fafc",
      fontSize: "13px",
      fontFamily: "'Inter', sans-serif",
      transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
      outline: "none",
      boxSizing: "border-box",
    },
    inputFocus: {
      borderColor: "#d4af37",
      background: "#0a0f1c",
      boxShadow: "0 0 0 3px rgba(212, 175, 55, 0.18)",
    },
    sectionTitle: {
      fontSize: "11px",
      fontWeight: "800",
      color: "#d4af37",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      marginBottom: "14px",
      marginTop: "24px",
      textTransform: "uppercase",
      letterSpacing: "0.12em",
      fontFamily: "'JetBrains Mono', monospace",
      borderBottom: "1px solid rgba(212, 175, 55, 0.2)",
      paddingBottom: "6px",
    },
    docBadge: {
      background: "rgba(212, 175, 55, 0.12)",
      color: "#d4af37",
      border: "1px solid rgba(212, 175, 55, 0.35)",
      padding: "4px 10px",
      borderRadius: "4px",
      fontWeight: "700",
      fontSize: "10px",
      letterSpacing: "0.08em",
      textTransform: "uppercase",
      fontFamily: "'JetBrains Mono', monospace",
    },
  },
};
