// Theme styles for documents and UI

export const S: Record<string, any> = {
  // We use any here for the nested structure while keeping the S object referenceable
  // but we should aim for CSSProperties where possible.
  page: {
    background: "#fff",
    color: "#1e293b",
    width: "100%",
    minHeight: "1056px", // 11 inches at 96dpi (US Letter)
    margin: "0 auto",
    padding: "60px 50px",
    position: "relative",
    fontFamily: "'Inter', sans-serif",
    fontSize: "12px",
    lineHeight: "1.5",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
    // Authentic security paper background pattern
    backgroundImage: `
      linear-gradient(45deg, rgba(200,210,230,0.1) 25%, transparent 25%, transparent 75%, rgba(200,210,230,0.1) 75%, rgba(200,210,230,0.1)),
      linear-gradient(45deg, rgba(200,210,230,0.1) 25%, transparent 25%, transparent 75%, rgba(200,210,230,0.1) 75%, rgba(200,210,230,0.1))
    `,
    backgroundSize: "20px 20px",
    backgroundPosition: "0 0, 10px 10px",
  },
  securityBorder: {
    position: "absolute",
    top: "10px",
    right: "10px",
    bottom: "10px",
    left: "10px",
    border: "1px solid rgba(0,0,0,0.05)",
    pointerEvents: "none",
    zIndex: 0,
  },
  microPrint: {
    position: "absolute",
    fontSize: "3px",
    color: "rgba(0,0,0,0.15)",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    overflow: "hidden",
  },
  header: {
    borderBottom: "3px double #1a1a2e",
    paddingBottom: "16px",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  logoBox: {
    width: "78px",
    height: "78px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  instBlock: { flex: 1 },
  instName: {
    fontSize: "17px",
    fontWeight: "700",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#1a1a2e",
    margin: 0,
  },
  instSub: {
    fontSize: "11px",
    color: "#555",
    margin: "2px 0 0",
    letterSpacing: "0.03em",
  },
  docTitle: {
    textAlign: "center",
    fontSize: "15px",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    margin: "20px 0",
    padding: "8px 0",
    borderTop: "1px solid #ccc",
    borderBottom: "1px solid #ccc",
    color: "#1a1a2e",
  },
  metaRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "11px",
    color: "#666",
    marginBottom: "20px",
  },
  section: { marginBottom: "20px" },
  sTitle: {
    fontSize: "12px",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    borderBottom: "1px solid #1a1a2e",
    paddingBottom: "4px",
    marginBottom: "10px",
    color: "#1a1a2e",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "12px" },
  th: {
    background: "#1a1a2e",
    color: "#fff",
    padding: "8px 12px",
    textAlign: "left",
    fontSize: "11px",
    letterSpacing: "0.05em",
    fontWeight: "600",
  },
  td: {
    padding: "7px 12px",
    borderBottom: "1px solid #e8e8e8",
    verticalAlign: "top",
  },
  tdAlt: {
    padding: "7px 12px",
    borderBottom: "1px solid #e8e8e8",
    background: "#f8f8fb",
    verticalAlign: "top",
  },
  fRow: { display: "flex", gap: "8px", marginBottom: "8px" },
  fLabel: {
    fontWeight: "700",
    minWidth: "160px",
    color: "#444",
    fontSize: "12px",
  },
  fVal: {
    flex: 1,
    borderBottom: "1px dotted #999",
    color: "#1a1a2e",
    fontSize: "12px",
  },
  sigSection: {
    marginTop: "40px",
    paddingTop: "20px",
    borderTop: "2px solid #1a1a2e",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  sigBlock: { textAlign: "center", flex: 1 },
  sigLine: {
    borderBottom: "1px solid #333",
    marginBottom: "6px",
    height: "35px",
  },
  sigLabel: { fontSize: "11px", color: "#555" },
  seal: {
    width: "90px",
    height: "90px",
    border: "3px double #1a1a2e",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    fontSize: "8px",
    fontWeight: "700",
    color: "#1a1a2e",
    textAlign: "center",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    padding: "6px",
    flexShrink: 0,
  },
  footer: {
    marginTop: "30px",
    paddingTop: "10px",
    borderTop: "1px solid #ccc",
    display: "flex",
    justifyContent: "space-between",
    fontSize: "10px",
    color: "#888",
  },
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "2px",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "0.05em",
  },
  infoBox: {
    background: "#f0f4ff",
    border: "1px solid #c7d3f5",
    borderLeft: "4px solid #1a1a2e",
    padding: "12px 16px",
    marginBottom: "16px",
    borderRadius: "2px",
  },
  totalRow: { background: "#1a1a2e", color: "#fff", fontWeight: "700" },
  watermark: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%,-50%) rotate(-35deg)",
    fontSize: "72px",
    fontWeight: "900",
    color: "rgba(26,26,46,0.04)",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    pointerEvents: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
    zIndex: 0,
  },
  // UI Specific Styles (Premium Rebrand)
  ui: {
    fontFamily: "'Outfit', sans-serif",
    container: {
      display: "flex",
      flexDirection: "row",
      gap: "32px",
      padding: "32px",
      minHeight: "calc(100vh - 120px)",
      background: "radial-gradient(circle at top right, #1e293b, #0f172a)",
    },
    formPanel: {
      width: "100%",
      background: "rgba(30, 41, 59, 0.7)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: "16px",
      padding: "28px",
      border: "1px solid rgba(255, 255, 255, 0.08)",
      boxShadow:
        "0 20px 50px rgba(0,0,0,0.4), inset 0 1px 1px rgba(255,255,255,0.1)",
      color: "#f1f5f9",
      height: "fit-content",
    },
    label: {
      display: "block",
      fontSize: "11px",
      fontWeight: "700",
      color: "#94a3b8",
      marginBottom: "8px",
      textTransform: "uppercase",
      letterSpacing: "0.1em",
      fontFamily: "'Outfit', sans-serif",
    },
    input: {
      width: "100%",
      background: "rgba(15, 23, 42, 0.5)",
      border: "1px solid rgba(71, 85, 105, 0.5)",
      borderRadius: "10px",
      padding: "12px 16px",
      color: "#f8fafc",
      fontSize: "14px",
      fontFamily: "'Inter', sans-serif",
      transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      outline: "none",
      marginBottom: "20px",
    },
    inputFocus: {
      borderColor: "#c9a84c",
      background: "rgba(15, 23, 42, 0.8)",
      boxShadow: "0 0 0 4px rgba(201,168,76,0.15), 0 4px 12px rgba(0,0,0,0.2)",
      transform: "translateY(-1px)",
    },
    sectionTitle: {
      fontSize: "13px",
      fontWeight: "800",
      color: "#c9a84c",
      display: "flex",
      alignItems: "center",
      gap: "10px",
      marginBottom: "20px",
      marginTop: "32px",
      textTransform: "uppercase",
      letterSpacing: "0.12em",
      fontFamily: "'Outfit', sans-serif",
      borderBottom: "1px dashed rgba(201,168,76,0.2)",
      paddingBottom: "10px",
    },
    docBadge: {
      background: "linear-gradient(135deg, #c9a84c 0%, #a68a3b 100%)",
      color: "#1a1a2e",
      padding: "6px 12px",
      borderRadius: "6px",
      fontWeight: "800",
      fontSize: "10px",
      textTransform: "uppercase",
      boxShadow: "0 4px 12px rgba(201,168,76,0.3)",
    },
  },
};
